name = "NeoGame"
author = "NBG4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67c2973252fc8089f6bca65d8c7d0fb82977e95c06a83a76b1290ed6112d85ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
