name = "NeoGame"
author = "NBG4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3743d9d42b35e4a8d1d82c2c2a0176a0362ddd48148db329597512c02394b1bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
