name = "NeoGame"
author = "NBG4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1d4f2ddb4159d453423a29b7b954b9139a3ed0e380a79c74f9ad8d75901def9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
